netgen_layouts:
    pagelayout: 'base.html.twig'

    value_types:
        doctrine:
            name: 'Local Doctrine'
            manual_items: false

    query_types:
        doctrine_search:
            name: 'Local Doctrine Search'
